name: medicapp

description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pinput: ^5.0.0
  intl_phone_field: ^3.2.0
  flutter_map: ^7.0.2  # or the latest version
  location: ^6.0.2
  flutter_spinkit: ^5.2.0
  http: ^1.2.0
  flutter_map_location_marker: ^9.1.1
  lottie: ^3.1.0
  introduction_screen: ^3.1.9
  flutter_svg: ^2.0.10+1
  intro_screen_onboarding_flutter: ^1.0.0
  carousel_slider: ^5.0.0
  dots_indicator: ^3.0.0
  curved_navigation_bar: ^1.0.6
  flutter_staggered_animations: ^1.1.1
  animated_background: ^2.0.0
  flutter_animated_button: ^2.0.3
  flutter_animate: ^4.5.0
  get: ^4.6.6
  animate_do: ^3.3.4
  swipable_stack: ^2.0.0
  overlapped_carousel: ^1.0.2
  flutter_zoom_drawer: ^3.0.0+1
  provider: ^6.1.2
  showcaseview: ^3.0.0
  flutter_local_notifications: ^17.2.2
  fluttertoast: ^8.0.9
  shared_preferences: ^2.3.2
  flutter_polyline_points: ^2.0.0
  url_launcher: ^6.1.5
  path_provider: ^2.1.4
  flutter_map_animations: ^0.7.1
  flutter_animarker: ^3.2.0
  qr_flutter: ^4.0.0
  onesignal_flutter: ^5.2.6


#  flutter_secure_storage: ^9.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/icons/

  fonts:
    - family: Main
      fonts:
        - asset: fonts/Zain-Regular.ttf
