name: medicapp

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pinput: ^2.2.12
  intl_phone_field: ^3.2.0
  flutter_map: ^6.1.0
  location: ^5.0.0
  flutter_spinkit: ^5.2.0
  http: ^1.2.0
  flutter_map_location_marker: ^8.0.8
  lottie: ^3.1.0
  introduction_screen: ^2.1.0
  flutter_svg: ^2.0.10+1
  intro_screen_onboarding_flutter: ^1.0.0
  carousel_slider: ^4.2.1
  dots_indicator: ^2.1.2
  curved_navigation_bar: ^1.0.6
  flutter_staggered_animations: ^1.1.1
  animated_background: ^2.0.0
  flutter_animated_button: ^2.0.3
  flutter_animate: ^4.5.0
  get: ^4.6.6
  animate_do: ^3.3.4
  swipable_stack: ^2.0.0
  overlapped_carousel: ^1.0.2
  flutter_zoom_drawer: ^3.0.0+1
  rive: ^0.13.3
  provider: ^6.1.2
  showcaseview: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    - assets/icons/
fonts:
  - family: Dancing Script
    fonts:
      - asset: assets/fonts/Danc.ttf

  - family: Caveat
    fonts:
      - asset: assets/fonts/Caveat.ttf

  - family: Changa-VariableFont_wght
    fonts:
      - asset: assets/fonts/Changa.ttf
  - family: PlaywriteCZ-VariableFont_wght
    fonts:
      - asset: assets/fonts/sp.ttf
  - family: Amiri
    fonts:
      - asset: assets/fonts/Amiri-BoldItalic.ttf
        weight: 700
        style: italic
  - family: Zain
    fonts:
      - asset: assets/fonts/Zain-Regular.ttf
